### PR TITLE
update the openapi generator

### PR DESCRIPTION
**Pull request by fabiokung**
The new generator has some fixes supporting ~schema v3 in v1.16~ custom type mappings for aliased types (OpenApiTools/openapi-generator#4182).

### CODE REVIEW

**Comment by fabiokung** [comment]
Required to make kubernetes-client/gen#117 work.

**Comment by fabiokung** [comment]
PTAL @yue9944882

**Comment by yue9944882** [comment]
> Required to make kubernetes-client#117 work.

thanks for updating this. just out of curiosity, what's new in 4.1.2 release?

**Comment by yue9944882** [comment]
thanks, merging it. i will append more commits for minor changes

**Pull request merged**
